export const GET_BODY_TRACK_REQUEST = 'GET_BODY_TRACK_REQUEST';
export const GET_BODY_TRACK_SUCCESS = 'GET_BODY_TRACK_SUCCESS';
export const GET_BODY_TRACK_FAIL = 'GET_BODY_TRACK_FAIL';

export const POST_BODY_TRACK_REQUEST = 'POST_BODY_TRACK_REQUEST';
export const POST_BODY_TRACK_SUCCESS = 'POST_BODY_TRACK_SUCCESS';
export const POST_BODY_TRACK_FAIL = 'POST_BODY_TRACK_FAIL';

export const UPDATE_BODY_TRACK_REQUEST = 'GET_PRODUCTS_REQUEST';
export const UPDATE_BODY_TRACK_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const UPDATE_BODY_TRACK_FAIL = 'GET_PRODUCTS_FAIL';

export const DELETE_BODY_TRACK_REQUEST = 'DELETE_BODY_TRACK_REQUEST';
export const DELETE_BODY_TRACK_SUCCESS = 'DELETE_BODY_TRACK_SUCCESS';
export const DELETE_BODY_TRACK_FAIL = 'DELETE_BODY_TRACK_FAIL';
